-- Create a table for public profiles (linked to Clerk Auth can be handled via application logic, here we just use the unique user ID string)
create table profiles (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique,
  full_name text,
  phone text,
  address text,
  user_type text default 'Individual',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text -- optional redundancy for easier DB browsing
);

-- Set up Row Level Security (RLS)
-- For this demo/hackathon ease, we will allow public read/write if you want to skip auth policies overhead
-- BUT best practice is:
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( true ); 
  -- In a real Supabase Auth setup, this would be 'auth.uid() = id', but with Clerk we manage ID match in app logic.
  -- To secure this with Clerk + Supabase properly, you'd usually use a custom JWT or just use the Service Role key for writes in API routes.
  -- For Client-side writing with Anon key (which we are doing), we need a simplified policy.
  
create policy "Users can update their own profile."
  on profiles for update
  using ( true ); 
  -- Again, simplified for 'Anon' key usage in this specific architecture where Supabase doesn't know the Clerk User yet legally.

-- Ideally, the app should use a backend API route to write with Service Role if we want true security, OR sync Clerk to Supabase Auth.
