-- Nyaaya AI Supabase Master Schema
-- Paste this entire file into the Supabase SQL Editor and run it.

-- 1. PROFILES TABLE
create table if not exists profiles (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique,
  full_name text,
  phone text,
  address text,
  age int,
  gender text,
  user_type text default 'Individual',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text
);

alter table profiles enable row level security;

create policy "Public Read Profiles" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (true);
create policy "Users can update their own profile" on profiles for update using (true) with check (true);


-- 2. LAWYER PROFILES TABLE
create table if not exists lawyer_profiles (
  id bigint generated by default as identity primary key,
  clerk_id text not null unique references profiles(clerk_id) on delete cascade,
  bar_council_id text,
  specialization text[], -- Array of strings e.g. ['Family', 'Criminal']
  experience_years integer,
  bio text,
  verification_status text default 'pending', -- pending, verified, rejected
  consultation_fee integer,
  rating numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table lawyer_profiles enable row level security;

create policy "Lawyer profiles are viewable by everyone" on lawyer_profiles for select using (true);
create policy "Lawyers can insert their own profile" on lawyer_profiles for insert with check (true);
create policy "Lawyers can update their own profile" on lawyer_profiles for update using (true);


-- 3. DOCUMENTS TABLE
create table if not exists documents (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Clerk ID
  file_url text not null,
  file_name text,
  file_type text,
  summary text,
  extracted_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table documents enable row level security;

create policy "Public read documents" on documents for select using (true);
create policy "Allow insert documents" on documents for insert with check (true);


-- 4. CHAT SESSIONS TABLE
create table if not exists chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id text not null, -- Clerk ID
  title text default 'New Chat',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table chat_sessions enable row level security;

create policy "Users can view sessions" on chat_sessions for select using (true);
create policy "Users can insert sessions" on chat_sessions for insert with check (true);
create policy "Users can update sessions" on chat_sessions for update using (true);
create policy "Users can delete sessions" on chat_sessions for delete using (true);


-- 5. CHAT MESSAGES TABLE
create table if not exists chat_messages (
  id uuid default gen_random_uuid() primary key,
  session_id uuid references chat_sessions(id) on delete cascade not null,
  role text not null, -- 'user' or 'assistant'
  content text,
  meta_data jsonb, -- For structured JSON responses
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table chat_messages enable row level security;

create policy "Users can view messages" on chat_messages for select using (true);
create policy "Users can insert messages" on chat_messages for insert with check (true);


-- 6. USER RIGHTS PROGRESS TABLE
create table if not exists user_rights_progress (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Clerk ID
  right_id text not null,
  right_title text,
  category text,
  status text default 'completed', -- 'in_progress', 'completed'
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, right_id)
);

alter table user_rights_progress enable row level security;

-- Universal true policy for Clerk Anonymous access
create policy "Allow access to own rows based on user_id column"
on user_rights_progress
for all
using (true) 
with check (true);
